version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: my_app_proxy
    ports:
      - "8081:80"    
      - "8443:443"   
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
      - ./src:/var/www/localhost/htdocs/ 
    depends_on:
      - app
      - phpmyadmin
    networks:
      - example1-network

  mysql1:
    image: mysql:5.7-debian
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=mydb6789tyui
      - MYSQL_ROOT_PASSWORD=mydb6789tyui
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./dbscripts:/dbscripts
    networks:
      - example1-network

  app:
    restart: unless-stopped
    build:
      context: ./platform
      dockerfile: Dockerfile
    environment:
      - MODE=development
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=mydb6789tyui
      - MYSQL_ROOT_PASSWORD=mydb6789tyui
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./src:/var/www/localhost/htdocs/
      - ./platform/httpd.conf:/etc/apache2/httpd.conf
      - ./platform/ssl.conf:/etc/apache2/conf.d/ssl.conf
      - ./platform/log:/var/log/
      - ./platform/php.ini:/etc/php7/php.ini
    extra_hosts:
      - "test:10.199.2.29"
    networks:
      - example1-network

  alpine:
    image: alpine:3.18
    command:
      - /bin/sh
      - -c
      - 'while true;do sleep 10000;done'
    networks:
      - example1-network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    links:
      - mysql1
    environment:
      - PMA_HOST=mysql1
      - MYSQL_ROOT_PASSWORD=mydb6789tyui
    networks:
      - example1-network

networks:
  example1-network:
    driver: bridge
