services:
  proxy:
    image: nginx:latest
    container_name: my_app_proxy
    ports:
      - "8081:80"    
      - "8443:443"   
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
      - ./frontend:/var/www/frontend  
    depends_on:
      - backend             
    networks:
      - example1-network

  backend:
    restart: unless-stopped
    build:
      context: ./platform
      dockerfile: Dockerfile
    environment:
      - MODE=development
    volumes:
      - ./backend:/var/www/localhost/htdocs/
      - ./platform/httpd.conf:/etc/apache2/httpd.conf
      - ./platform/ssl.conf:/etc/apache2/conf.d/ssl.conf
      - ./platform/log:/var/log/
      - ./platform/php.ini:/etc/php7/php.ini
    extra_hosts:
      - "test:10.199.2.29"
    networks:
      - example1-network

networks:
  example1-network:
    driver: bridge