# Versi 3 sudah usang dan bisa dihapus
services:
  proxy:
    image: nginx:latest
    container_name: my_app_proxy
    ports:
      - "8081:80"    
      - "8443:443"    # Kita tetap menggunakan 443 di container
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
      - ./src:/var/www/localhost/htdocs/  
    depends_on:
      - app           # Hanya 'app' yang jadi dependensi
    networks:
      - example1-network

  app:
    restart: unless-stopped
    build:
      context: ./platform
      dockerfile: Dockerfile
    environment:
      - MODE=development
      # Semua variabel MYSQL dihapus
    volumes:
      - ./src:/var/www/localhost/htdocs/
      - ./platform/httpd.conf:/etc/apache2/httpd.conf
      - ./platform/ssl.conf:/etc/apache2/conf.d/ssl.conf
      - ./platform/log:/var/log/
      - ./platform/php.ini:/etc/php7/php.ini
    extra_hosts:
      - "test:10.199.2.29"
    networks:
      - example1-network

# Layanan mysql1, alpine, dan phpmyadmin dihapus dari sini

networks:
  example1-network:
    driver: bridge